### ISSUE TITLE
在 Mac m1 上编译似乎有问题

### ISSUE THREAD

**Issue by ihewro** [demopark/electron-api-demos-Zh_CN#40]
```
warning "@octokit/rest > @octokit/plugin-request-log@1.0.3" has unmet peer dependency "@octokit/core@>=3".
[4/4] 🔨  Building fresh packages...
[-/7] ⠠ waiting...
[-/7] ⠠ waiting...
[-/7] ⠠ waiting...
[4/7] ⠠ electron-chromedriver
error /Users/hewro/Documents/study/electron-api-demos-Zh_CN/node_modules/spectron/node_modules/electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments:
Directory: /Users/hewro/Documents/study/electron-api-demos-Zh_CN/node_modules/spectron/node_modules/electron-chromedriver
Output:
/Users/hewro/Documents/study/electron-api-demos-Zh_CN/node_modules/spectron/node_modules/electron-chromedriver/download-chromedriver.js:19
  if (err != null) throw err
                   ^

Error: Failed to find Electron v3.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-darwin-arm64.zip
    at Request.<anonymous> (/Users/hewro/Documents/study/electron-api-demos-Zh_CN/node_modules/nugget/index.js:169:61)
    at Request.emit (node:events:378:20)
    at Request.onRequestResponse (/Users/hewro/Documents/study/electron-api-demos-Zh_CN/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (node:events:378:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:502:22)
 
```

* 您使用哪个版本的 Node.js?
15.11

**Comment by ihewro** [comment]
看了一下应该是 electron和spectron的版本太低了导致的，spectron低版本中用的 chromedriver是 3.0.0没有 amd 版本，版本太高导致 link.import 用不了，如果方便的话可以打包一下
