### ISSUE TITLE
https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-darwin-arm64.zip不存在

### ISSUE THREAD

**Issue by boy119** [demopark/electron-api-demos-Zh_CN#47]
* 您使用什么操作系统?  mac
* 您使用哪个版本的 Node.js? v16.4.1
* 请问这个错误怎么解决？谢谢
2851 error Error: Failed to find Electron v3.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-darwin-arm64.zip
2851 error     at Request.<anonymous> (/Users/apple/txt/electron/electron-api-demos-Zh_CN/node_modules/nugget/index.js:169:61)
2851 error     at Request.emit (node:events:394:28)
2851 error     at Request.onRequestResponse (/Users/apple/txt/electron/electron-api-demos-Zh_CN/node_modules/request/request.js:1066:10)
2851 error     at ClientRequest.emit (node:events:394:28)
2851 error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
2851 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
2851 error     at TLSSocket.socketOnData (node:_http_client:487:22)
2851 error     at TLSSocket.emit (node:events:394:28)
2851 error     at addChunk (node:internal/streams/readable:312:12)
2851 error     at readableAddChunk (node:internal/streams/readable:287:9)

**Comment by supersea** [comment]
遇到了一样的问题

**Comment by james-curtis** [comment]
设置镜像地址为 `https://mirrors.huaweicloud.com/electron`
